import { getSolutionCategories,solutionEvaluationRows } from '@/lib/solutions/model';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft,ArrowUpRight } from 'lucide-react';
import { requireFounder,isReviewer,getSolution,getEvents } from '@/lib/solutions/server';
import { isSolutionId,statuses } from '@/lib/solutions/model';
import { StatusBadge } from '@/components/solutions/status-badge';
import { SolutionEditor } from '@/components/solutions/solution-editor';
import { ReviewForm } from '@/components/solutions/review-form';
export const metadata={title:'Mi postulación | shwcs',robots:{index:false,follow:false}};
export default async function SolutionPage(props:{params: Promise<{id:string}>}) {
 const params = await props.params;
 const account=await requireFounder();if(!isSolutionId(params.id))notFound();const reviewer=await isReviewer(account.id);const solution=await getSolution(params.id,account.id,reviewer);if(!solution)notFound();const events=await getEvents(solution.id);const owner=solution.owner_id===account.id;return <section className="account-page">
  <Link href={owner?'/account/solutions':'/account/review'} className="mb-8 inline-flex items-center gap-2 text-sm text-stone-500"><ArrowLeft className="size-4" />{owner?'Mis soluciones':'Revisión editorial'}</Link>
  <Link href={`/account/solutions/${solution.id}/preview`} target="_blank" className="mb-6 ml-5 inline-flex items-center gap-1.5 rounded-full border border-stone-200 bg-white px-3 py-1.5 text-xs font-medium text-stone-700 shadow-sm transition-all hover:bg-stone-50 hover:text-stone-900 focus:outline-none focus:ring-2 focus:ring-[#365DC4]/50 focus:ring-offset-2">Vista previa del borrador guardado <ArrowUpRight className="size-3.5 text-stone-400" aria-hidden="true"/></Link>
  {owner&&solution.published_data&&<Link href={`/account/solutions/${solution.id}/trust`} className="mb-6 ml-5 inline-flex text-sm text-[#365DC4]">Verificar dominio →</Link>}
  <header className="mb-9 border-b border-stone-200 pb-8"><div className="mb-4 flex flex-wrap items-center gap-3"><StatusBadge status={solution.status} />{solution.published_data&&<Link href={`/soluciones/${solution.id}`} target="_blank" className="inline-flex items-center gap-1 text-xs text-stone-500">Ver ficha publicada<ArrowUpRight className="size-3" /><span className="sr-only"> (otra pestaña)</span></Link>}</div><h1 className="break-words text-3xl font-semibold tracking-tight sm:text-4xl">{solution.data.name||'Tu nueva solución.'}</h1><p className="mt-4 max-w-xl text-sm leading-relaxed text-stone-500">{statuses[solution.status].next}</p>{solution.published_data&&solution.status!=='published'&&<p className="mt-3 text-xs text-stone-500">La versión aprobada sigue publicada mientras preparas esta actualización.</p>}</header>
  <div className={owner?"space-y-12":"grid items-start gap-12 lg:grid-cols-[minmax(0,1fr)_240px]"}><div className="min-w-0 space-y-8">
  {(solution.status==='pending'||solution.status==='published'||!owner)&&<details open={!owner||solution.status==='pending'} className="border-b border-stone-200 pb-6"><summary className="cursor-pointer text-sm font-medium">Información de la postulación</summary><dl className="mt-5 space-y-4">{[['Tipo',`${solution.data.kind} · ${getSolutionCategories(solution.data).join(' · ')}`],['Problema',solution.data.problem],['Para quién',solution.data.audience],['Cuándo no encaja',solution.data.notFor??'Por completar'],['Demo',solution.data.demoUrl??'Por completar'],['Sitio',solution.data.website],['Contacto privado',solution.data.contactEmail],['Creadores',solution.data.founders?.map(person=>[person.name,person.role,person.bio,...person.links.map(link=>link.label+': '+link.url)].filter(Boolean).join('\n')).join('\n\n')||'Por completar'],['Redes del proyecto',solution.data.projectLinks?.map(link=>link.label+': '+link.url).join('\n')||'Por completar'],...solutionEvaluationRows(solution.data),['Enlace de evidencia',solution.data.evidenceUrl??'Por completar']].map(([label,value])=><div key={label}><dt className="text-xs text-stone-400">{label}</dt><dd className="mt-1 whitespace-pre-wrap break-words text-sm leading-relaxed text-stone-700">{value}</dd></div>)}</dl></details>}
  {owner?<SolutionEditor key={`${solution.id}-${solution.version}`} solution={solution} />:solution.status==='pending'&&<ReviewForm id={solution.id} version={solution.version} />}
  </div><aside className="border-t border-stone-200 pt-6 lg:border-t-0 lg:pt-0"><details><summary className="mb-5 cursor-pointer text-sm font-semibold">Seguimiento de la postulación</summary>{events.length?<ol className="space-y-6">{events.map(event=><li key={event.id} className="border-l border-stone-300 pl-4"><p className="text-xs font-medium text-stone-700">{statuses[event.status]?.label??'Actualización editorial'}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-relaxed text-stone-500">{event.message}</p><time className="mt-2 block text-xs text-stone-400">{new Date(event.created_at).toLocaleDateString('es-MX',{day:'numeric',month:'short',timeZone:'UTC'})}</time></li>)}</ol>:<p className="text-sm leading-relaxed text-stone-500">Todavía no la has enviado. Aquí aparecerán los avances y comentarios del equipo.</p>}</details></aside></div>
  </section>;
}
