"use client";

import { useCallback,useEffect,useRef,useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Bell,Check,LoaderCircle,Plus,RefreshCw,X } from 'lucide-react';
import { actionButtonStyle } from '@/lib/brand-colors';

export type AccountNotification={id:string;title:string;href:string;readAt:string|null;createdAt:string};
type Cursor={before:string;beforeId:string};
type Feed={notifications:AccountNotification[];unreadCount:number;hasMore:boolean;nextCursor:Cursor|null};

function notificationDate(value:string){const date=new Date(value),today=new Date();if(date.toDateString()===today.toDateString())return date.toLocaleTimeString('es-MX',{hour:'numeric',minute:'2-digit'});return date.toLocaleDateString('es-MX',{day:'numeric',month:'short',timeZone:'America/Mexico_City'});}

export function AccountUtilities({initialNotifications,initialUnreadCount,initialHasMore}:{initialNotifications:AccountNotification[];initialUnreadCount:number;initialHasMore:boolean}){
 const [open,setOpen]=useState(false),[notifications,setNotifications]=useState(initialNotifications),[unread,setUnread]=useState(initialUnreadCount),[hasMore,setHasMore]=useState(initialHasMore),[cursor,setCursor]=useState<Cursor|null>(()=>{const last=initialNotifications.at(-1);return last?{before:last.createdAt,beforeId:last.id}:null;}),[loading,setLoading]=useState(false),[loadingMore,setLoadingMore]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState('');
 const root=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null),router=useRouter();
 function close(returnFocus=false){setOpen(false);if(returnFocus)requestAnimationFrame(()=>trigger.current?.focus());}
 async function mutate(body:Record<string,unknown>){const response=await fetch('/api/notifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error();}
 const refresh=useCallback(async(silent=false)=>{if(!silent)setLoading(true);setError('');try{const response=await fetch('/api/notifications',{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error();const feed=await response.json() as Feed;setNotifications(feed.notifications);setUnread(feed.unreadCount);setHasMore(feed.hasMore);setCursor(feed.nextCursor);}catch{if(!silent)setError('No pudimos actualizar tus avisos.');}finally{if(!silent)setLoading(false);}},[]);
 useEffect(()=>{if(!open)return;void refresh();const pointer=(event:PointerEvent)=>{if(!root.current?.contains(event.target as Node))close();};const keyboard=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();close(true);}};document.addEventListener('pointerdown',pointer);document.addEventListener('keydown',keyboard);return()=>{document.removeEventListener('pointerdown',pointer);document.removeEventListener('keydown',keyboard);};},[open,refresh]);
 useEffect(()=>{const interval=window.setInterval(()=>{if(document.visibilityState==='visible'&&!open)void refresh(true);},30000);return()=>window.clearInterval(interval);},[open,refresh]);
 async function loadMore(){if(!cursor||loadingMore)return;setLoadingMore(true);setError('');try{const params=new URLSearchParams(cursor);const response=await fetch(`/api/notifications?${params}`,{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error();const feed=await response.json() as Feed;setNotifications(values=>{const ids=new Set(values.map(item=>item.id));return [...values,...feed.notifications.filter(item=>!ids.has(item.id))];});setUnread(feed.unreadCount);setHasMore(feed.hasMore);setCursor(feed.nextCursor);}catch{setError('No pudimos cargar avisos anteriores.');}finally{setLoadingMore(false);}}
 async function openNotification(item:AccountNotification){close();if(!item.readAt){setNotifications(values=>values.map(value=>value.id===item.id?{...value,readAt:new Date().toISOString()}:value));setUnread(value=>Math.max(0,value-1));try{await mutate({action:'read',id:item.id});}catch{setNotifications(values=>values.map(value=>value.id===item.id?{...value,readAt:null}:value));setUnread(value=>value+1);}}router.push(item.href);}
 async function readAll(){if(pending||!unread)return;setPending(true);setError('');const previous=notifications,previousUnread=unread;setNotifications(values=>values.map(value=>({...value,readAt:value.readAt??new Date().toISOString()})));setUnread(0);try{await mutate({action:'read-all'});}catch{setNotifications(previous);setUnread(previousUnread);setError('No pudimos marcar los avisos.');}finally{setPending(false);}}
 return <div ref={root} className="fixed right-4 top-[92px] z-30 flex items-center gap-2 lg:right-6 lg:top-6">
  <Link href="/account/solutions/new" aria-label="Postular solución" title="Postular solución" style={actionButtonStyle} className="action-button flex size-11 items-center justify-center rounded-full"><Plus className="size-5" aria-hidden="true"/></Link>
  <button ref={trigger} type="button" aria-label={unread?`Avisos, ${unread} sin leer`:'Avisos'} aria-expanded={open} aria-controls="account-notifications" title="Avisos" onClick={()=>setOpen(value=>!value)} className="action-button relative flex size-11 items-center justify-center rounded-full bg-white text-stone-600 shadow-[0_5px_16px_-10px_rgba(41,37,36,0.45)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#365DC4]"><Bell className="size-[19px]" aria-hidden="true"/>{unread>0&&<span aria-hidden="true" className="absolute right-2.5 top-2.5 size-2 rounded-full bg-[#365DC4] ring-2 ring-white"/>}</button>
  {open&&<section id="account-notifications" aria-label="Avisos" className="sidebar-reveal absolute right-0 top-[calc(100%+0.75rem)] w-[min(380px,calc(100vw-2rem))] overflow-hidden rounded-[24px] border border-stone-200 bg-white shadow-[0_24px_65px_-24px_rgba(41,37,36,0.38)]">
   <header className="flex items-center justify-between gap-4 border-b border-stone-100 px-5 py-4"><div><h2 className="font-semibold tracking-tight">Avisos</h2><p className="mt-0.5 text-xs text-stone-400">{unread?`${unread} sin leer`:'Todo al día'}</p></div><div className="flex items-center gap-1">{unread>0&&<button type="button" disabled={pending} onClick={()=>void readAll()} aria-label="Marcar todos como leídos" title="Marcar todos como leídos" className="flex size-9 items-center justify-center rounded-full text-[#365DC4] transition-colors hover:bg-[#E4EBFC] disabled:opacity-40">{pending?<LoaderCircle className="size-4 animate-spin motion-reduce:animate-none"/>:<Check className="size-4"/>}</button>}<button type="button" disabled={loading} onClick={()=>void refresh()} aria-label="Actualizar avisos" title="Actualizar avisos" className="flex size-9 items-center justify-center rounded-full text-stone-500 transition-colors hover:bg-stone-100 disabled:opacity-40"><RefreshCw className={`size-3.5 ${loading?'animate-spin motion-reduce:animate-none':''}`}/></button><button type="button" onClick={()=>close(true)} aria-label="Cerrar avisos" className="flex size-9 items-center justify-center rounded-full text-stone-500 transition-colors hover:bg-stone-100"><X className="size-4"/></button></div></header>
   {loading&&!notifications.length?<div className="space-y-4 px-5 py-6" aria-label="Cargando avisos">{[0,1,2].map(item=><div key={item} className="flex gap-3"><span className="mt-1 size-2 rounded-full bg-stone-200"/><span className="space-y-2"><span className="block h-3 w-52 animate-pulse rounded bg-stone-100 motion-reduce:animate-none"/><span className="block h-2.5 w-16 animate-pulse rounded bg-stone-100 motion-reduce:animate-none"/></span></div>)}</div>:notifications.length?<div className="max-h-[min(60svh,480px)] divide-y divide-stone-100 overflow-y-auto">{notifications.map(item=><button key={item.id} type="button" onClick={()=>void openNotification(item)} className="group flex w-full items-start gap-3 px-5 py-4 text-left transition-colors hover:bg-stone-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-inset focus-visible:outline-[#365DC4]"><span className={`mt-1.5 size-2 shrink-0 rounded-full ${item.readAt?'bg-stone-200':'bg-[#365DC4]'}`}/><span className="min-w-0 flex-1"><span className={`block text-sm leading-snug ${item.readAt?'text-stone-500':'font-medium text-stone-800'}`}>{item.title}</span><time className="mt-2 block text-xs text-stone-400" dateTime={item.createdAt}>{notificationDate(item.createdAt)}</time></span></button>)}{hasMore&&<button type="button" disabled={loadingMore} onClick={()=>void loadMore()} className="flex w-full items-center justify-center gap-2 px-5 py-4 text-xs text-[#365DC4] hover:bg-stone-50 disabled:opacity-50">{loadingMore&&<LoaderCircle className="size-3.5 animate-spin motion-reduce:animate-none"/>}{loadingMore?'Cargando…':'Ver anteriores'}</button>}</div>:<div className="px-6 py-10 text-center"><Bell className="mx-auto size-6 text-stone-300"/><p className="mt-3 text-sm text-stone-500">Aquí aparecerán respuestas y cambios importantes.</p></div>}
   {error&&<p role="alert" className="border-t border-stone-100 px-5 py-3 text-xs text-[#A94E35]">{error}</p>}
   <footer className="border-t border-stone-100 px-5 py-3"><Link href="/account/settings/notifications" onClick={()=>close()} className="text-xs text-stone-500 transition-colors hover:text-[#365DC4]">Preferencias de correo →</Link></footer>
  </section>}
 </div>;
}
