import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ChangelogStory } from '@/components/editorial/changelog-story';
import { ProjectStory } from '@/components/editorial/project-story';
const pages:Record<string,{title:string;intro:string;sections:[string,string][]}>={
 criterios:{title:'Qué revisamos.',intro:'Buscamos proyectos que expliquen con claridad qué resuelven y para quién.',sections:[['Información suficiente','Nombre, categorías, problema, cliente ideal, sitio y contacto. Precio, alcance, límites y evidencia ayudan a evaluar el encaje.'],['Evidencia y transparencia','Los casos y resultados se presentan con sus fuentes. Una ficha publicada no equivale a una auditoría de seguridad, solvencia ni resultados. La verificación DNS solo acredita control del dominio en la fecha indicada.'],['Contenido responsable','No aceptamos suplantación, afirmaciones engañosas ni contenido ilícito. Puedes reportar una ficha desde su página. Una publicación puede retirarse tras revisión.']]},
 proceso:{title:'De idea a publicación.',intro:'Tu ficha tiene seguimiento desde tu cuenta.',sections:[['1. Prepara tu ficha','Guarda un borrador y añade contexto, creadores, enlaces, capturas y una demo si tienes.'],['2. Envía a revisión','El equipo puede publicar, pedir cambios o rechazar con una explicación. Postular no garantiza publicación ni hay un plazo de respuesta prometido.'],['3. Mantén la información al día','Los cambios en un borrador no alteran la versión pública hasta aprobarse. Revisa tus avisos para consultar decisiones y solicitudes.']]},
 faq:{title:'Preguntas frecuentes.',intro:'Lo esencial para descubrir y publicar proyectos.',sections:[['¿Quién puede usar una cuenta?','Una persona puede explorar soluciones y publicar sus proyectos. Comprador y fundador son vistas de trabajo; no permisos editoriales.'],['¿Mis guardados son públicos?','Tus guardados y notas son privados. Las listas solo se comparten si eliges publicarlas. Guardar un proyecto no avisa a su fundador ni crea una solicitud.'],['¿Cómo contacto a un proyecto?','Desde su ficha puedes enviar una solicitud con contexto y consentimiento. Las respuestas se consultan en la cuenta; los avisos por correo dependen de tu verificación, preferencias y disponibilidad del servicio.'],['¿shwcs recomienda contratar?','Publicar facilita evaluar y contactar, pero no garantiza resultados. Confirma condiciones directamente con el proyecto antes de contratar.']]},
 'el-proyecto':{title:'Proyectos que vale la pena conocer.',intro:'shwcs conecta empresas con software, agencias y servicios que pueden ayudarles a resolver problemas concretos.',sections:[['Para quien busca','Descubre por necesidad, guarda opciones, compáralas y conversa con sus equipos.'],['Para quien construye','Presenta tu proyecto con contexto y evidencia. Mantén tu ficha clara y responde a quienes quieren conocerla.'],['Cómo presentamos la información','Distinguimos datos declarados, revisión editorial y control comprobado de dominio. El orden del catálogo es editorial; no es una puntuación de calidad.']]},
 blog:{title:'Ideas para elegir mejor.',intro:'Notas de shwcs sobre software, servicios y las decisiones que ayudan a una empresa a avanzar.',sections:[['Próximamente','Estamos preparando la primera serie editorial. Publicaremos análisis claros, casos y preguntas útiles; no contenido hecho para llenar espacio.'],['Qué encontrarás','Guías para compradores, aprendizajes de fundadores y contexto para entender qué solución encaja con cada problema.']]},
 changelog:{title:'Lo que cambia en shwcs.',intro:'Un registro claro de las mejoras que afectan cómo descubres, evalúas y presentas proyectos.',sections:[['Agosto de 2026','Abrimos guardados y listas, listas públicas de la comunidad, formularios guiados para fundadores, avisos dentro de la cuenta y métricas de fichas.'],['Siguiente actualización','Publicaremos aquí los cambios que ya estén disponibles. Las ideas y funciones en desarrollo seguirán fuera del registro hasta que sean reales.']]},
 privacidad:{title:'Tu información.',intro:'Este resumen describe cómo funciona el tratamiento de datos en la beta de shwcs.',sections:[['Cuenta y acceso','Almacenamos correo, contraseña protegida con un hash, sesiones y el perfil que decidas completar. Si vinculas Google, guardamos su identificador y correo para autenticarte. No conservamos acceso a Gmail ni permisos sobre tus archivos.'],['Lo público y lo privado','Las fichas aprobadas son públicas. Tus listas son privadas por defecto; si publicas una, se comparten su título, descripción pública, firma y proyectos. Su propósito y notas siguen privados, al igual que tus borradores, contactos de acceso y guardados. Puedes volver a hacer privada una lista, aunque no podemos retirar copias que otros hayan hecho. Al solicitar contacto autorizas compartir los datos indicados con el destinatario mostrado.'],['Actividad y proveedores','Neon aloja la base. El proveedor de correo, cuando esté configurado, procesa los avisos autorizados. Registramos totales de visitas y clics sin identificadores de visitante; respetamos DNT/GPC. Los controles de abuso usan contadores técnicos temporales.'],['Controles disponibles','Puedes editar tu perfil, borrar guardados/listas, retirar solicitudes y desactivar avisos por correo desde tu cuenta. Los datos publicados por terceros deben revisarse en sus propias políticas.'],['Antes del lanzamiento general','La identificación formal del responsable, contacto para derechos de privacidad, plazos de conservación y aviso integral están pendientes de validación. Este resumen operativo no los sustituye.']]},
 terminos:{title:'Uso de la beta.',intro:'shwcs es un espacio para descubrir y presentar proyectos. No procesa la contratación entre empresas y proveedores.',sections:[['Información honesta','Comparte información que tengas derecho a publicar y solicita autorización antes de presentar colaboradores. No suplantes personas o proyectos.'],['Decisiones de compra','Alcance, precio, disponibilidad y contrato se acuerdan directamente con cada proveedor. Las fichas, visitas y solicitudes no garantizan ventas ni resultados.'],['Moderación','El equipo puede pedir cambios o retirar contenido tras revisión. Los reportes se gestionan dentro de shwcs. No hay una garantía de publicación por completar el formulario.'],['Alcance de este texto','Estas son reglas operativas de la beta. Los términos legales completos requieren validación del responsable antes de un lanzamiento general.']]},
 cookies:{title:'Cookies y medición.',intro:'El acceso usa cookies necesarias para mantener y proteger tu sesión.',sections:[['Sesión','La cookie de acceso es HttpOnly, SameSite y Secure en producción. El flujo de Google utiliza una cookie temporal de seguridad que caduca en diez minutos.'],['Métricas agregadas','El contador de visitas y clics de fichas no crea una cookie analítica ni un identificador de visitante. Puede omitir eventos por bloqueadores, límites técnicos o preferencias DNT/GPC.'],['Servicios externos','Los sitios, demos y redes que abras tienen sus propias políticas. shwcs no controla sus cookies.']]}
};
export async function generateMetadata({params}:{params:Promise<{info:string}>}){const {info}=await params;return {title:pages[info]?`${pages[info].title} | shwcs`:'shwcs',robots:['privacidad','terminos'].includes(info)?{index:false,follow:true}:undefined};}
export default async function InfoPage({params}:{params:Promise<{info:string}>}){const {info}=await params,page=pages[info];if(!page)notFound();if(info==='el-proyecto')return <ProjectStory/>;if(info==='changelog')return <ChangelogStory/>;return <article className="mx-auto max-w-4xl px-6 py-16 sm:py-24"><h1 className="text-4xl font-semibold tracking-tight sm:text-5xl">{page.title}</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-stone-500">{page.intro}</p><div className="mt-12 space-y-8">{page.sections.map(([title,text])=><section key={title} className="border-t border-stone-200 pt-6"><h2 className="text-xl font-medium">{title}</h2><p className="mt-3 leading-relaxed text-stone-600">{text}</p></section>)}</div><Link href="/#catalogo" className="mt-10 inline-block text-sm text-[#365DC4]">Explorar proyectos →</Link></article>;}
