import { ExpandingSearch } from '@/components/search/expanding-search';
import Link from 'next/link';
import { Plus,ArrowRight,ArrowLeft,ChevronDown,Check } from 'lucide-react';
import { getPublicCollections } from '@/lib/library/community';
import { BoardCard } from '@/components/library/board-card';
import { CommunityIcon } from '@/components/library/community-icon';
import { actionButtonStyle } from '@/lib/brand-colors';
import { communitySorts,type CommunitySort } from '@/lib/library/community-model';
import { solutionCategories } from '@/lib/solutions/model';
export const dynamic='force-dynamic';
export const metadata={title:'Listas de la comunidad | shwcs',description:'Descubre selecciones de software, agencias y servicios compartidas por la comunidad.'};
export default async function CommunityPage({searchParams}:{searchParams:Promise<{q?:string;category?:string;page?:string;sort?:string}>}){
 const params=await searchParams,query=typeof params.q==='string'?params.q.trim().slice(0,100):'';
 const category=solutionCategories.find(value=>value===params.category)??'';
 const sort:CommunitySort=communitySorts.includes(params.sort as CommunitySort)?params.sort as CommunitySort:'recent';
 const page=Math.max(1,Math.min(1000,Number.parseInt(String(params.page??'1'),10)||1));
 const filtered=Boolean(category||query||sort!=='recent');
 const {collections,hasMore}=await getPublicCollections({category,query,page,sort});
 const destination=(nextCategory=category,nextPage=1,nextSort:CommunitySort=sort)=>{const value=new URLSearchParams({...(query?{q:query}:{}),...(nextSort!=='recent'?{sort:nextSort}:{}),...(nextCategory?{category:nextCategory}:{}),...(nextPage>1?{page:String(nextPage)}:{})}).toString();return value?`/comunidad?${value}`:'/comunidad';};
 return <section className={`mx-auto w-full max-w-[1500px] px-5 pb-24 sm:px-10 lg:px-16 ${filtered?'pt-20':'pt-16 sm:pt-24'}`}>{!filtered&&<header className="mb-10 flex flex-wrap items-end justify-between gap-6"><div><h1 className="text-4xl font-semibold tracking-[-0.045em] sm:text-6xl">Buenas selecciones.<br/>Nuevas posibilidades.</h1><p className="mt-5 text-base text-stone-500">Listas de proyectos, hechas por la comunidad.</p></div><Link href="/account/lists" style={actionButtonStyle} className="action-button inline-flex items-center gap-3 rounded-full px-5 py-3 text-sm font-medium">Crear mi lista<Plus className="size-4" aria-hidden="true"/></Link></header>}
 <div className="mb-10 border-b border-stone-200 pb-6"><div className="flex flex-col gap-5"><nav aria-label="Categorías de listas" className="selector-tabs"><Link href={destination('')} aria-current={!category?'page':undefined} className="selector-tab">Todas</Link>{solutionCategories.map(item=><Link key={item} href={destination(category===item?'':item)} aria-current={category===item?'page':undefined} className="selector-tab">{item}</Link>)}</nav>
 <div className="relative flex w-full items-center justify-end gap-3"><ExpandingSearch className="community-search !absolute left-0 !ml-0 sm:!relative sm:left-auto sm:!ml-auto" key={`${category}-${query}-${sort}`} label="Buscar listas de la comunidad" placeholder="Encuentra una selección" defaultValue={query} action="/comunidad" fields={{...(category?{category}:{}),...(sort!=='recent'?{sort}:{})}} maxLength={100}/><details className="group relative"><summary data-selected={sort!=='recent'} className="selector-dropdown-trigger [&::-webkit-details-marker]:hidden"><span>{sort==='popular'?'Más populares':'Más recientes'}</span><ChevronDown aria-hidden="true" className="size-4 transition-transform duration-200 group-open:rotate-180 motion-reduce:transition-none"/></summary><div className="absolute right-0 top-[calc(100%+0.5rem)] z-20 w-56 overflow-hidden rounded-2xl border border-stone-200 bg-white p-2 text-stone-700 shadow-[0_18px_45px_-20px_rgba(41,37,36,0.35)]"><Link href={destination(category,1,'recent')} aria-current={sort==='recent'?'page':undefined} className={`flex items-center justify-between rounded-xl px-4 py-3 text-sm transition-colors hover:bg-stone-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#365DC4] ${sort==='recent'?'selector-menu-active':''}`}>Más recientes{sort==='recent'&&<Check aria-hidden="true" className="size-4"/>}</Link><Link href={destination(category,1,'popular')} aria-current={sort==='popular'?'page':undefined} className={`flex items-center justify-between rounded-xl px-4 py-3 text-sm transition-colors hover:bg-stone-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#365DC4] ${sort==='popular'?'selector-menu-active':''}`}>Más populares{sort==='popular'&&<Check aria-hidden="true" className="size-4"/>}</Link></div></details></div></div></div>
 {collections.length?<div className="grid gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{collections.map(collection=><BoardCard key={collection.id} board={{id:collection.id,name:collection.name,count:collection.count,covers:collection.covers,visibility:collection.visibility}} href={`/comunidad/${collection.id}`} byline={collection.curator} stats={{likes:collection.likes,saves:collection.saves,comments:collection.comments}}/>)}</div>:<div className="flex min-h-72 flex-col items-center justify-center py-12 text-center"><CommunityIcon className="mb-5 size-12 text-stone-300"/><h2 className="text-2xl font-medium tracking-tight">{query||category||page>1?'Todavía no hay listas aquí.':'Tu selección puede ser la primera.'}</h2><p className="mt-3 max-w-sm text-sm leading-relaxed text-stone-500">{query||category||page>1?'Prueba otra categoría o explora todas las selecciones.':'Reúne proyectos que merecen conocerse y comparte tu lista.'}</p><Link href={query||category||page>1?'/comunidad':'/account/lists'} className="mt-6 inline-flex items-center gap-2 text-sm text-[#365DC4]">{query||category||page>1?'Ver todas':'Crear una lista'}<ArrowRight className="size-4"/></Link></div>}
 {(page>1||hasMore)&&<nav aria-label="Páginas de la comunidad" className="mt-12 flex items-center justify-between border-t border-stone-200 pt-6">{page>1?<Link href={destination(category,page-1)} className="inline-flex items-center gap-2 text-sm text-[#365DC4]"><ArrowLeft className="size-4"/>Anterior</Link>:<span/>}<span className="text-xs text-stone-400">Página {page}</span>{hasMore?<Link href={destination(category,page+1)} className="inline-flex items-center gap-2 text-sm text-[#365DC4]">Siguiente<ArrowRight className="size-4"/></Link>:<span/>}</nav>}
 </section>;
}
