"use client";
import { useEffect,useRef,useState } from 'react';
import Image from 'next/image';
import { ArrowLeft,ArrowRight,Plus,Trash2,Upload } from 'lucide-react';
import { actionButtonStyle } from '@/lib/brand-colors';
import { libraryButton,libraryError,libraryField } from '@/components/library/client';
import type { SolutionScreenshot } from '@/lib/solutions/model';
type Asset={id:string;width:number;height:number;in_use:boolean};
export function MediaEditor({solutionId,value,onChange,onBusy}:{solutionId:string;value:SolutionScreenshot[];onChange:(images:SolutionScreenshot[])=>void;onBusy:(busy:boolean)=>void}){
 const [assets,setAssets]=useState<Asset[]>([]),[loading,setLoading]=useState(true),[pending,setPending]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState<string|null>(null);const busy=useRef(false),file=useRef<HTMLInputElement>(null);
 const base=`/api/solutions/${solutionId}/media`;
 async function load(){setLoading(true);try{const r=await fetch(base,{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error);setAssets(data.assets);}catch(error){setError(libraryError(error));}finally{setLoading(false);}}
 useEffect(()=>{const controller=new AbortController();fetch(base,{cache:'no-store',signal:controller.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);setAssets(data.assets);}).catch(e=>{if(e.name!=='AbortError')setError(libraryError(e));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[base]);
 async function upload(selected:File){if(busy.current)return;setError('');if(selected.size>2*1024*1024){setError('Cada imagen admite hasta 2 MB.');return;}busy.current=true;setPending(true);onBusy(true);try{const r=await fetch(base,{method:'POST',headers:{'Content-Type':selected.type},body:selected,signal:AbortSignal.timeout(20000)}),data=await r.json();if(!r.ok)throw new Error(data.error);setAssets(current=>[data.asset,...current]);if(value.length<4)onChange([...value,{id:data.asset.id,caption:''}]);}catch(error){setError(libraryError(error));}finally{busy.current=false;setPending(false);onBusy(false);if(file.current)file.current.value='';}}
 function move(index:number,direction:number){const next=[...value];[next[index],next[index+direction]]=[next[index+direction],next[index]];onChange(next);}
 return <section className="space-y-5 border-t border-stone-200 pt-7"><div><h3 className="text-lg font-medium">Muestra cómo funciona.</h3><p className="mt-2 text-sm leading-relaxed text-stone-500">Hasta 4 capturas reales. JPG, PNG o WebP, máximo 2 MB cada una. Oculta datos personales de clientes antes de subirlas.</p><p className="mt-2 text-xs text-stone-400">Subir no publica: guarda el borrador y envíalo a revisión. Se conserva la ficha aprobada anterior.</p></div>
 {value.length>0&&<ol className="grid gap-5 sm:grid-cols-2">{value.map((item,index)=><li key={item.id} className="min-w-0"><div className="relative aspect-[4/3] overflow-hidden rounded-xl border border-stone-200 bg-white"><Image src={base+'/'+item.id} alt={item.caption||'Captura pendiente de descripción'} fill sizes="(max-width: 640px) 100vw, 400px" className="object-contain"/></div><label className="mt-3 block text-xs text-stone-500">¿Qué muestra la captura {index+1}?<input value={item.caption} disabled={pending} maxLength={180} onChange={event=>onChange(value.map(image=>image.id===item.id?{...image,caption:event.target.value}:image))} className={libraryField} placeholder="Por ejemplo: seguimiento de cuentas por cobrar"/></label><div className="mt-3 flex items-center gap-3"><button type="button" aria-label={`Mover captura ${index+1} antes`} disabled={pending||index===0} onClick={()=>move(index,-1)} className="rounded-lg p-2 disabled:opacity-30"><ArrowLeft className="size-4"/></button><button type="button" aria-label={`Mover captura ${index+1} después`} disabled={pending||index===value.length-1} onClick={()=>move(index,1)} className="rounded-lg p-2 disabled:opacity-30"><ArrowRight className="size-4"/></button><button type="button" disabled={pending} onClick={()=>onChange(value.filter(image=>image.id!==item.id))} className="ml-auto text-xs text-stone-500">Quitar de la ficha</button></div></li>)}</ol>}
 <div><input ref={file} id="solution-screenshot-upload" type="file" accept="image/png,image/jpeg,image/webp" disabled={pending||value.length>=4} className="sr-only" onChange={event=>{const selected=event.target.files?.[0];if(selected)void upload(selected);}}/><button type="button" disabled={pending||value.length>=4} onClick={()=>file.current?.click()} style={actionButtonStyle} className={libraryButton}><Upload className="size-4" aria-hidden="true"/>{pending?'Procesando…':'Subir captura'}</button><span className="ml-3 text-xs text-stone-500">{value.length}/4 en esta ficha</span></div>
 <details><summary className="cursor-pointer text-xs text-stone-500">Archivos de esta solución ({assets.length}/12)</summary><p className="mt-3 text-xs leading-relaxed text-stone-500">Reutiliza capturas o elimina archivos que ya no estén guardados ni publicados. Quitar de la ficha no borra el archivo.</p><button type="button" onClick={()=>void load()} disabled={pending||loading} className="my-3 text-xs text-[#365DC4]">{loading?'Cargando…':'Actualizar archivos'}</button><ul className="space-y-3">{assets.map(asset=><li key={asset.id} className="flex items-center gap-3"><Image src={base+'/'+asset.id} alt="Archivo de captura" width={64} height={48} sizes="64px" className="h-12 w-16 rounded object-contain"/><span className="flex-1 text-xs text-stone-500">{asset.width} × {asset.height}{asset.in_use?' · Guardada o publicada':''}</span>{!value.some(item=>item.id===asset.id)&&<><button type="button" aria-label="Añadir archivo a la ficha" disabled={pending||value.length>=4} onClick={()=>onChange([...value,{id:asset.id,caption:''}])} className="rounded-lg p-2 text-[#365DC4] disabled:opacity-30"><Plus className="size-4"/></button><button type="button" aria-label="Eliminar archivo sin uso" disabled={pending||asset.in_use} onClick={()=>setConfirm(asset.id)} className="rounded-lg p-2 text-stone-500 disabled:opacity-30"><Trash2 className="size-4"/></button></>}</li>)}</ul></details>
 {confirm&&<div className="text-sm text-stone-500"><p>Eliminarás este archivo. Si está seleccionado sin guardar en otra pestaña, tendrás que subirlo de nuevo.</p><div className="mt-3 flex gap-4"><button type="button" disabled={pending} onClick={async()=>{if(busy.current)return;busy.current=true;setPending(true);onBusy(true);setError('');try{const r=await fetch(base+'/'+confirm,{method:'DELETE',signal:AbortSignal.timeout(15000)}),data=await r.json();if(!r.ok)throw new Error(data.error);setAssets(current=>current.filter(asset=>asset.id!==confirm));setConfirm(null);}catch(error){setError(libraryError(error));}finally{busy.current=false;setPending(false);onBusy(false);}}} className="text-[#A94E35]">Eliminar archivo</button><button type="button" disabled={pending} onClick={()=>setConfirm(null)}>Cancelar</button></div></div>}
 {error&&<p role="alert" className="text-sm text-[#A94E35]">{error}</p>}
 </section>;
}
