"use client";
import {Plus,Trash2} from 'lucide-react';
import {publicLinkKinds,type PublicLink,type SolutionFounder} from '@/lib/solutions/profile';
import {actionButtonStyle} from '@/lib/brand-colors';
export const solutionInput='mt-2 w-full rounded-xl border border-stone-300 bg-transparent px-4 py-3 text-base outline-none transition-colors focus:border-[#365DC4] focus:ring-1 focus:ring-[#365DC4]';
export function PublicLinksEditor({links,onChange,limit=6,label}:{links:PublicLink[];onChange:(links:PublicLink[])=>void;limit?:number;label:string}){
 return <section aria-label={label}><div className="space-y-4">{links.map((link,index)=><div key={index} className="grid items-end gap-3 sm:grid-cols-[155px_minmax(0,1fr)_40px]"><label className="text-xs text-stone-500">Tipo de enlace {index+1}<select className={solutionInput} value={link.label} onChange={e=>onChange(links.map((item,i)=>i===index?{...item,label:e.target.value as PublicLink['label']}:item))}>{publicLinkKinds.map(kind=><option key={kind}>{kind}</option>)}</select></label><label className="min-w-0 text-xs text-stone-500">URL {index+1}<input type="url" className={solutionInput} value={link.url} maxLength={500} placeholder="https://" onChange={e=>onChange(links.map((item,i)=>i===index?{...item,url:e.target.value}:item))}/></label><button type="button" aria-label={`Eliminar enlace ${index+1}`} onClick={()=>onChange(links.filter((_,i)=>i!==index))} className="justify-self-end rounded-lg p-3 text-stone-500 hover:bg-stone-200/50"><Trash2 className="size-4"/></button></div>)}</div>{links.length<limit&&<button type="button" onClick={()=>onChange([...links,{label:'LinkedIn',url:''}])} style={actionButtonStyle} className="action-button mt-5 inline-flex items-center gap-2 rounded-full px-5 py-3 text-sm"><Plus className="size-4"/>Añadir enlace</button>}<p className="mt-3 text-xs text-stone-400">{links.length}/{limit} enlaces · Se publicarán al aprobar la ficha.</p></section>;
}
export function FoundersEditor({value,onChange}:{value:SolutionFounder[];onChange:(people:SolutionFounder[])=>void}){
 function update(index:number,patch:Partial<SolutionFounder>){onChange(value.map((person,i)=>i===index?{...person,...patch}:person));}
 return <div><p className="mb-6 text-sm leading-relaxed text-stone-500">Comparte solo información que estas personas autoricen a hacer pública. No copiamos los datos privados de tu cuenta.</p><div className="space-y-8">{value.map((person,index)=><fieldset key={index} className="space-y-5 border-b border-stone-200 pb-7"><legend className="mb-4 text-sm font-medium">Persona {index+1}</legend><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm">Nombre público<input className={solutionInput} value={person.name} maxLength={100} onChange={e=>update(index,{name:e.target.value})} placeholder="Nombre o nombre profesional"/></label><label className="text-sm">Rol en el proyecto<input className={solutionInput} value={person.role} maxLength={80} onChange={e=>update(index,{role:e.target.value})} placeholder="Fundador, cofundadora, responsable…"/></label></div><label className="block text-sm">Una breve presentación<textarea className={solutionInput} value={person.bio} maxLength={400} rows={3} onChange={e=>update(index,{bio:e.target.value})} placeholder="Experiencia y relación con el proyecto."/></label><PublicLinksEditor label={`Redes de la persona ${index+1}`} links={person.links} limit={4} onChange={links=>update(index,{links})}/><button type="button" onClick={()=>onChange(value.filter((_,i)=>i!==index))} className="text-sm text-stone-500">Quitar esta persona</button></fieldset>)}</div>{value.length<3&&<button type="button" onClick={()=>onChange([...value,{name:'',role:'',bio:'',links:[]}])} style={actionButtonStyle} className="action-button mt-5 inline-flex items-center gap-2 rounded-full px-5 py-3 text-sm"><Plus className="size-4"/>Añadir persona</button>}</div>;
}
