"use client";
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowRight,ArrowLeft,Check,ArrowUpRight} from 'lucide-react';
import gsap from 'gsap';
import {MediaEditor} from './media-editor';
import {CompletenessGuide} from './completeness-guide';
import {FoundersEditor,PublicLinksEditor,solutionInput as input} from './profile-editor';
import {actionButtonStyle,brandColors,solutionCategoryTones} from '@/lib/brand-colors';
import {solutionCategories,solutionErrors,solutionEvaluationFields,solutionEvaluationRows,getSolutionCategories,type FounderSolution,type SolutionData} from '@/lib/solutions/model';
import {solutionQuestions,questionIndex,questionErrors} from '@/lib/solutions/questions';
export function SolutionEditor({solution}:{solution:FounderSolution}){
 const router=useRouter(),[data,setData]=useState(solution.data),[step,setStep]=useState(questionIndex(solution.editor_question,solution.step)),[version,setVersion]=useState(solution.version),[dirty,setDirty]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[mediaBusy,setMediaBusy]=useState(false),[editing,setEditing]=useState(solution.status!=='published');
 const busy=useRef(false),title=useRef<HTMLHeadingElement>(null),panel=useRef<HTMLDivElement>(null),initialized=useRef(false),form=useRef<HTMLFormElement>(null);
 const question=solutionQuestions[step],blocked=pending||mediaBusy;
 const guideQuestion=(phase:number,key?:string)=>questionIndex(({basics:'identity',fit:'problem',scope:'scope',visual:'screenshots',demo:'demo',commercial:'pricing',support:'delivery',people:'founders',evidence:'evidence'} as Record<string,string>)[key??''],phase);
 useEffect(()=>{if(!dirty)return;const warn=(event:BeforeUnloadEvent)=>event.preventDefault();window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 useEffect(()=>{if(!editing)return;if(initialized.current){title.current?.focus({preventScroll:true});panel.current?.scrollIntoView({block:'start',behavior:'instant'});}initialized.current=true;const motion=gsap.matchMedia();motion.add('(prefers-reduced-motion: no-preference)',()=>{gsap.fromTo(panel.current,{opacity:0,y:10},{opacity:1,y:0,duration:0.22,ease:'power2.out',clearProps:'opacity,transform'});});return()=>motion.revert();},[step,editing]);
 function update(patch:Partial<SolutionData>){setData(current=>({...current,...patch}));setDirty(true);setError('');setMessage('');}
 async function save(action:'save'|'submit',nextStep=step,exit=false){
  if(busy.current||mediaBusy)return;setError('');setMessage('');
  if(action==='submit'){const errors=solutionErrors(data);if(Object.keys(errors).length){const first=solutionQuestions.findIndex(item=>(item.fields as readonly string[]).some(key=>key in errors));if(first>=0)setStep(first);setError(Object.values(errors)[0]!);return;}}
  busy.current=true;setPending(true);try{const next=solutionQuestions[nextStep],response=await fetch(`/api/solutions/${solution.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,data,step:next.phase,question:next.id,version}),signal:AbortSignal.timeout(15000)}),result=await response.json();if(!response.ok)throw new Error(result.error);setVersion(result.version);setDirty(false);setStep(nextStep);setMessage(action==='submit'?'Enviada a revisión.':'Avance guardado.');if(exit)router.push('/account/solutions');else if(action==='submit')router.refresh();}
  catch(failure){setError(failure instanceof Error&&!['TimeoutError','TypeError','SyntaxError'].includes(failure.name)?failure.message:'No pudimos confirmar el guardado. Conservamos tus cambios; comprueba el borrador antes de repetir.');}finally{busy.current=false;setPending(false);}
 }
 function goNext(){if(blocked)return;if(question.id==='review'){void save('submit');return;}const errors=questionErrors(data,step);if(errors.length){setError(errors[0]);return;}void save('save',step+1);}
 if(solution.status==='pending')return <p className="border-y border-stone-200 py-6 text-sm leading-relaxed text-stone-600">Tu postulación está en revisión. Podrás editar cuando termine; puedes consultar la vista previa de lo enviado.</p>;
 if(!editing)return <><CompletenessGuide data={data} id={solution.id} onChoose={(phase,key)=>{setStep(guideQuestion(phase,key));setEditing(true);}}/><button type="button" onClick={()=>setEditing(true)} style={actionButtonStyle} className="action-button rounded-full px-6 py-3 text-sm">Preparar actualización</button></>;
 function field(key:'name'|'problem'|'audience'|'notFor'|'demoUrl'|'website'|'contactEmail'|'evidenceUrl',label:string,limit:number,rows=1,placeholder=''){
  const props={value:data[key]??'',maxLength:limit,className:input,placeholder,onChange:(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>update({[key]:e.target.value})};
  return <label className="block text-sm">{label}{rows>1?<textarea {...props} rows={rows}/>:<input {...props} type={key==='contactEmail'?'email':['website','demoUrl','evidenceUrl'].includes(key)?'url':'text'}/>}</label>;
 }
 function evaluation(key:typeof solutionEvaluationFields[number]['key']){const item=solutionEvaluationFields.find(value=>value.key===key)!;return <label key={key} className="block text-sm">{item.prompt}<textarea value={data[key]??''} maxLength={item.limit} rows={3} className={input} placeholder={item.placeholder} onChange={e=>update({[key]:e.target.value})}/></label>;}
 return <form ref={form} noValidate aria-label="Postular mi solución" aria-busy={blocked} onSubmit={event=>{event.preventDefault();goNext();}} onKeyDown={event=>{if(event.nativeEvent.isComposing)return;if(event.key==='Enter'&&(event.ctrlKey||event.metaKey)&&question.id!=='review'){event.preventDefault();goNext();}else if(event.key==='Enter'&&event.target instanceof HTMLInputElement&&event.target.type!=='file'){event.preventDefault();if(question.id!=='review')goNext();}}}>
 <div className="mb-9 flex flex-wrap items-center justify-between gap-4 border-b border-stone-200 pb-5"><div className="flex items-center gap-4"><span className="text-xs text-stone-500" aria-live="polite">Pregunta {step+1} de {solutionQuestions.length}</span><div role="progressbar" aria-label="Recorrido de la ficha" aria-valuenow={step+1} aria-valuemin={1} aria-valuemax={solutionQuestions.length} className="h-1 w-24 overflow-hidden rounded-full bg-stone-200"><div className="h-full bg-[#365DC4] transition-[width] motion-reduce:transition-none" style={{width:`${(step+1)/solutionQuestions.length*100}%`}}/></div></div><div className="flex flex-wrap items-center gap-4"><span className="text-xs text-stone-400" role="status">{pending?'Guardando…':mediaBusy?'Procesando captura…':dirty?'Cambios sin guardar':'Avance guardado'}</span><button type="button" disabled={blocked} onClick={()=>void save('save',step,true)} className="inline-flex items-center gap-1.5 rounded-full border border-stone-200 bg-white px-3 py-1.5 text-sm font-medium text-stone-700 shadow-sm transition-all hover:bg-stone-50 hover:text-stone-900 focus:outline-none focus:ring-2 focus:ring-[#365DC4]/50 focus:ring-offset-2 disabled:opacity-50">Guardar y salir <ArrowUpRight className="size-3.5 text-stone-400" aria-hidden="true"/></button></div></div>
 <div className="grid items-start gap-12 xl:grid-cols-[minmax(0,1fr)_220px]"><div ref={panel} className="min-w-0 scroll-mt-28"><div className="mb-8"><h2 ref={title} tabIndex={-1} className="text-3xl font-medium leading-tight tracking-[-0.03em] outline-none sm:text-4xl">{question.title}</h2><p className="mt-4 text-sm leading-relaxed text-stone-500">{question.hint}</p>{question.optional&&<p className="mt-3 text-xs text-stone-400">Opcional · Puedes completarlo después.</p>}</div>
 <fieldset disabled={blocked} className="min-h-[180px] space-y-6">
 {question.id==='identity'&&field('name','Nombre del proyecto',100,1,'Por ejemplo: Cord')}
 {question.id==='categories'&&<><fieldset><legend className="mb-3 text-sm">Tipo de solución</legend><div className="grid gap-3 sm:grid-cols-3">{['Software','Agencia','Servicio'].map((kind,i)=><label key={kind} className="cursor-pointer"><input type="radio" name="solution-kind" value={kind} checked={data.kind===kind} onChange={()=>update({kind})} className="peer sr-only"/><span className="flex items-center gap-3 rounded-xl border border-stone-300 p-4 text-sm transition-colors peer-checked:border-[#365DC4] peer-checked:bg-[#E4EBFC] peer-checked:text-[#365DC4] peer-focus-visible:outline peer-focus-visible:outline-2 peer-focus-visible:outline-[#365DC4]"><span className="text-xs opacity-60">{String.fromCharCode(65+i)}</span>{kind}</span></label>)}</div></fieldset><fieldset><legend className="mb-3 text-sm">Categorías · Puedes elegir varias</legend><div className="grid gap-3 sm:grid-cols-2">{solutionCategories.map(category=>{const selected=getSolutionCategories(data).includes(category),tone=brandColors[solutionCategoryTones[category]];return <label key={category} className="flex cursor-pointer items-center justify-between gap-3 rounded-xl border p-4 text-sm transition-colors" style={selected?{backgroundColor:tone.soft,color:tone.solid,borderColor:tone.solid}:{borderColor:'#d6d3d1'}}>{category}<input type="checkbox" checked={selected} className="size-4 accent-[#365DC4]" onChange={()=>{const categories=selected?getSolutionCategories(data).filter(value=>value!==category):[...getSolutionCategories(data),category];update({categories,category:categories[0]??''});}}/></label>})}</div></fieldset></>}
 {question.id==='problem'&&field('problem','El problema y cómo lo resuelves',1500,5,'Sin términos vagos: ¿qué puede hacer mejor una empresa contigo?')}
 {question.id==='audience'&&field('audience','Tu cliente ideal',800,4,'Industria, tamaño, equipo y necesidad.')}
 {question.id==='scope'&&<>{evaluation('scope')}{field('notFor','¿Cuándo no es la opción adecuada?',500,3,'Necesidades que no cubres o condiciones que necesitas.')}</>}
 {question.id==='founders'&&<FoundersEditor value={data.founders??[]} onChange={founders=>update({founders})}/>}
 {question.id==='links'&&<PublicLinksEditor label="Redes y enlaces del proyecto" links={data.projectLinks??[]} onChange={projectLinks=>update({projectLinks})}/>}
 {question.id==='screenshots'&&<MediaEditor solutionId={solution.id} value={data.screenshots??[]} onBusy={setMediaBusy} onChange={screenshots=>update({screenshots})}/>}
 {question.id==='demo'&&field('demoUrl','Enlace a la demo o recorrido',500,1,'https://')}
 {question.id==='pricing'&&evaluation('pricing')}
 {question.id==='delivery'&&<>{evaluation('implementation')}{evaluation('integrations')}{evaluation('support')}</>}
 {question.id==='evidence'&&<>{evaluation('evidence')}{field('evidenceUrl','Enlace al caso, portafolio o evidencia',500,1,'https://')}</>}
 {question.id==='contact'&&<>{field('website','Sitio oficial · Público',500,1,'https://')}{field('contactEmail','Correo de revisión · Privado',254)}<p className="text-xs text-stone-500">Este correo no aparecerá en la ficha. Las solicitudes de compradores llegan a tu cuenta.</p></>}
 {question.id==='review'&&<><dl className="grid gap-x-8 gap-y-6 sm:grid-cols-2">{[['Proyecto',data.name],['Tipo y categorías',`${data.kind} · ${getSolutionCategories(data).join(' · ')}`],['Problema',data.problem],['Cliente ideal',data.audience],['Cuándo no encaja',data.notFor],['Demo',data.demoUrl],['Capturas',data.screenshots?.map(image=>image.caption).join(' · ')],['Sitio',data.website],['Contacto privado',data.contactEmail],...solutionEvaluationRows(data),['Enlace de evidencia',data.evidenceUrl],['Creadores',data.founders?.map(person=>[person.name,person.role,person.bio,...person.links.map(link=>`${link.label}: ${link.url}`)].filter(Boolean).join('\n')).join('\n\n')],['Redes del proyecto',data.projectLinks?.map(link=>`${link.label}: ${link.url}`).join('\n')]].map(([label,value])=><div key={label}><dt className="text-xs text-stone-400">{label}</dt><dd className="mt-2 whitespace-pre-wrap break-words text-sm leading-relaxed">{value||'Por completar'}</dd></div>)}</dl><p className="border-t border-stone-200 pt-6 text-sm text-stone-500">Al enviar, el equipo revisará la ficha y sus enlaces públicos. No se publica automáticamente. Si ya tienes una versión aprobada, seguirá visible mientras revisamos esta actualización.</p></>}
 </fieldset>
 {error&&<p role="alert" className="mt-6 text-sm text-[#A94E35]">{error}</p>}{message&&<p role="status" className="mt-5 inline-flex items-center gap-2 text-xs text-stone-500"><Check className="size-3"/>{message}</p>}
 <div className="mt-9 flex flex-wrap items-center gap-4"><button type="submit" disabled={blocked} style={actionButtonStyle} className="action-button inline-flex items-center gap-3 rounded-full px-6 py-3 text-sm font-medium disabled:opacity-40">{question.id==='review'?'Enviar a revisión':'Continuar'}<ArrowRight className="size-4"/></button>{step>0&&<button type="button" disabled={blocked} onClick={()=>void save('save',step-1)} className="inline-flex items-center gap-2 rounded-full px-3 py-3 text-sm text-stone-500 disabled:opacity-40"><ArrowLeft className="size-4"/>Anterior</button>}{question.id!=='review'&&<span className="text-xs text-stone-400">Enter para continuar · Ctrl/⌘ + Enter en textos</span>}</div>
 </div><aside className="min-w-0 border-t border-stone-200 pt-6 xl:sticky xl:top-10 xl:border-t-0 xl:pt-0"><details><summary className="cursor-pointer text-sm text-stone-500">Ir a otra pregunta</summary><nav aria-label="Preguntas de la ficha" className="mt-4 space-y-1">{solutionQuestions.map((item,index)=><button key={item.id} type="button" disabled={blocked} aria-current={index===step?'step':undefined} onClick={()=>void save('save',index)} className={`flex w-full gap-3 rounded-lg px-2 py-2 text-left text-xs ${index===step?'bg-[#E4EBFC] text-[#365DC4]':'text-stone-500 hover:bg-stone-200/30'}`}><span className="tabular-nums">{String(index+1).padStart(2,'0')}</span>{item.title}</button>)}</nav></details><p className="mt-6 text-xs leading-relaxed text-stone-400">Cada vez que avanzas guardamos el borrador. Nada se publica hasta que envíes y el equipo lo apruebe.</p><CompletenessGuide data={data} id={solution.id} onChoose={blocked?undefined:(phase,key)=>void save('save',guideQuestion(phase,key))}/></aside></div>
 </form>;
}
