"use client";
import { useRef,useState } from 'react';
import Link from 'next/link';
import { MessageCircle,Trash2 } from 'lucide-react';
import type { SolutionComment } from '@/lib/solutions/social';
import { actionButtonStyle } from '@/lib/brand-colors';
async function mutate(data:Record<string,unknown>){const response=await fetch('/api/solutions/social',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const body=await response.json();if(response.status===401)throw Object.assign(Error(body.error),{login:true});if(!response.ok)throw Error(body.error);return body;}
// Like lives in the sidebar now (see like-button.tsx); this section is only
// the comments — its own count, its own list, same endpoint underneath.
export function SolutionSocial({id,initialCommentsCount,comments:initialComments,initialName=''}:{id:string;initialCommentsCount:number;comments:SolutionComment[];initialName?:string}){
 const [commentsCount,setCommentsCount]=useState(initialCommentsCount),[comments,setComments]=useState(initialComments),[name,setName]=useState(initialName),[comment,setComment]=useState(''),[pending,setPending]=useState(''),[error,setError]=useState(''),[login,setLogin]=useState(false);const lock=useRef(false),commentId=useRef<string|null>(null);
 return <section className="mt-14 border-t border-stone-200 pt-8" aria-labelledby="solution-conversation">{login&&<p className="mt-4 text-sm text-stone-500"><Link href={`/sign-in?next=${encodeURIComponent('/soluciones/'+id)}`} className="text-[#365DC4] underline underline-offset-4">Inicia sesión o crea una cuenta</Link> para participar.</p>}{error&&<p role="alert" className="mt-4 text-sm text-[#A94E35]">{error}</p>}
 <div className="max-w-3xl"><h2 id="solution-conversation" className="flex items-center gap-2 text-2xl font-semibold tracking-tight"><MessageCircle className="size-5"/>{commentsCount} {commentsCount===1?'comentario':'comentarios'}</h2><form className="mt-6 grid gap-3" onSubmit={async event=>{event.preventDefault();if(lock.current)return;lock.current=true;setPending('comment');setError('');setLogin(false);commentId.current??=crypto.randomUUID();try{const result=await mutate({action:'comment',solutionId:id,name,comment,commentId:commentId.current});if(result.created){setComments(values=>[{id:result.id,name:name.trim(),body:comment.trim(),createdAt:result.createdAt,mine:true},...values]);setCommentsCount(value=>value+1);}setComment('');commentId.current=null;}catch(e){if(e instanceof Error&&'login'in e)setLogin(true);else setError(e instanceof Error?e.message:'No pudimos publicar.');}finally{lock.current=false;setPending('');}}}><label className="sr-only" htmlFor="comment-name">Nombre o alias público</label><input id="comment-name" maxLength={60} required value={name} onChange={event=>setName(event.target.value)} placeholder="Tu nombre o alias público" className="rounded-2xl border border-stone-200 bg-transparent px-4 py-3 text-sm outline-none focus:border-[#365DC4]"/><label className="sr-only" htmlFor="comment-body">Comentario</label><textarea id="comment-body" maxLength={500} required value={comment} onChange={event=>setComment(event.target.value)} placeholder="Comparte una observación o pregunta útil." rows={3} className="rounded-2xl border border-stone-200 bg-transparent px-4 py-3 text-sm outline-none focus:border-[#365DC4]"/><div className="flex items-center justify-between gap-4"><p className="text-xs text-stone-400">Tu nombre y comentario serán públicos.</p><button disabled={!!pending} style={actionButtonStyle} className="action-button rounded-full px-5 py-3 text-sm">{pending==='comment'?'Publicando…':'Comentar'}</button></div></form>
 <div className="mt-8 divide-y divide-stone-200">{comments.map(item=><article key={item.id} className="py-5"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-medium">{item.name}</p><time className="mt-1 block text-xs text-stone-400" dateTime={item.createdAt}>{new Date(item.createdAt).toLocaleDateString('es-MX',{day:'numeric',month:'short',year:'numeric'})}</time></div>{item.mine&&<button aria-label="Eliminar mi comentario" className="rounded-full p-2 text-stone-400 hover:bg-stone-100 hover:text-[#A94E35]" onClick={async()=>{try{await mutate({action:'delete-comment',solutionId:id,commentId:item.id});setComments(values=>values.filter(value=>value.id!==item.id));setCommentsCount(value=>Math.max(0,value-1));}catch(e){setError(e instanceof Error?e.message:'No pudimos eliminarlo.');}}}><Trash2 className="size-4"/></button>}</div><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-relaxed text-stone-600">{item.body}</p></article>)}{!comments.length&&<p className="py-7 text-sm text-stone-500">Sé la primera persona en comentar esta ficha.</p>}</div></div></section>;
}
