import Link from 'next/link';
import { ArrowRight,Camera,ClipboardCheck,Columns3,FolderPlus,Inbox,Send,UserRound,Wallet,Users,Briefcase,Workflow,Scale } from 'lucide-react';
import type { FounderSolution } from '@/lib/solutions/model';
import type { BuyerBoard } from '@/lib/library/model';
import { solutionChecklist } from '@/lib/solutions/completeness';
import { brandColors,solutionCategoryTones } from '@/lib/brand-colors';
export function NextActions({founder,buyer,solutions,boards,unorganized}:{founder:boolean;buyer:boolean;solutions:FounderSolution[];boards:BuyerBoard[];unorganized:number}){
 const tasks=founder?solutions.filter(solution=>solution.status!=='pending').map(solution=>{
  const missing=solutionChecklist(solution.data).find(item=>!item.done);
  const review=solution.status==='changes_requested'||solution.status==='rejected';
  if(!review&&!missing)return null;
  return {href:`/account/solutions/${solution.id}`,title:review?'Revisar comentarios':missing?.key==='visual'?'Añadir capturas':`Completar ${missing?.label.toLowerCase()}`,detail:solution.data.name||'Tu proyecto',Icon:review?ClipboardCheck:missing?.key==='visual'?Camera:ClipboardCheck,tone:brandColors.sage,priority:review?0:1};
 }).filter(task=>task!==null).sort((a,b)=>a.priority-b.priority).slice(0,3):[];
 const ready=buyer?boards.filter(board=>board.covers.length>=2).slice(0,2):[];
 const shortcuts=[...(founder?[{href:'/account/opportunities',label:'Oportunidades',Icon:Inbox,tone:brandColors.terracotta}]:[]),...(buyer?[{href:'/account/contacts',label:'Mis contactos',Icon:Send,tone:brandColors.blue}]:[]),{href:'/account/settings/profile',label:'Mi perfil',Icon:UserRound,tone:brandColors.lavender}];
 return <>{(tasks.length>0||ready.length>0||(buyer&&unorganized>0))&&<section aria-label="Para avanzar"><h2 className="mb-5 text-xl font-semibold tracking-tight">Para avanzar</h2><div className="grid gap-x-8 md:grid-cols-2">{tasks.map(({href,title,detail,Icon,tone})=><ActionRow key={href} href={href} title={title} detail={detail} Icon={Icon} tone={tone}/>)}{buyer&&unorganized>0&&<ActionRow href="/account/saved?list=none" title="Organizar guardados" detail={`${unorganized} ${unorganized===1?'proyecto sin lista':'proyectos sin lista'}`} Icon={FolderPlus} tone={brandColors.amber}/>} {ready.map(board=><ActionRow key={board.id} href={`/account/lists/${board.id}`} title="Comparar opciones" detail={board.name} Icon={Columns3} tone={brandColors.lavender}/>)}</div></section>}
 <section aria-label="A mano"><h2 className="mb-5 text-xl font-semibold tracking-tight">A mano</h2><div className="flex flex-wrap gap-3">{shortcuts.map(({href,label,Icon,tone})=><Link key={href} href={href} className="group inline-flex items-center gap-3 rounded-2xl border border-stone-200 px-4 py-3 text-sm transition-colors hover:bg-white"><span className="flex size-9 items-center justify-center rounded-xl" style={{backgroundColor:tone.soft,color:tone.solid}}><Icon className="size-4" aria-hidden="true"/></span>{label}<ArrowRight className="ml-3 size-4 text-stone-400 transition-transform group-hover:translate-x-1 motion-reduce:transform-none" aria-hidden="true"/></Link>)}</div></section></>;
}
function ActionRow({href,title,detail,Icon,tone}:{href:string;title:string;detail:string;Icon:typeof Camera;tone:{soft:string;solid:string}}){return <Link href={href} className="group flex min-w-0 items-center gap-4 border-b border-stone-200 py-5"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl" style={{backgroundColor:tone.soft,color:tone.solid}}><Icon className="size-4" aria-hidden="true"/></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{title}</span><span className="mt-1 block truncate text-xs text-stone-500">{detail}</span></span><ArrowRight className="size-4 shrink-0 text-stone-400 transition-transform group-hover:translate-x-1 motion-reduce:transform-none" aria-hidden="true"/></Link>;}
const discovery=[{label:'Finanzas',Icon:Wallet},{label:'Nómina',Icon:Users},{label:'Agencias',Icon:Briefcase},{label:'Operación',Icon:Workflow},{label:'Legal',Icon:Scale}];
export function ExploreNeeds(){return <section><div className="mb-5 flex items-center justify-between gap-4"><h2 className="text-xl font-semibold tracking-tight">Explora por necesidad</h2><Link href="/#catalogo" className="shrink-0 text-sm text-[#365DC4]">Ver catálogo →</Link></div><div className="flex flex-wrap gap-3">{discovery.map(({label,Icon})=>{const tone=brandColors[solutionCategoryTones[label]];return <Link key={label} href={`/?q=${encodeURIComponent(label)}#catalogo`} className="action-button inline-flex items-center gap-2 rounded-full px-5 py-3 text-sm" style={{backgroundColor:tone.soft,color:tone.solid}}><Icon className="size-4" aria-hidden="true"/>{label}</Link>;})}</div></section>;}
