import Link from 'next/link';
import { notFound,redirect } from 'next/navigation';
import { requireBuyer } from '@/lib/library/server';
import { isSolutionId } from '@/lib/solutions/model';
import { getContact,contactEvents } from '@/lib/contacts/server';
import { contactStatuses } from '@/lib/contacts/model';
import { ContactActions,RefreshContacts } from '@/components/contacts/forms';
export async function ContactDetail({id,incoming=false}:{id:string;incoming?:boolean}){
 if(!isSolutionId(id))notFound();const base=incoming?'/account/opportunities':'/account/contacts';const account=await requireBuyer(base+'/'+id),request=await getContact(id,account.id);if(!request)notFound();
 if(incoming&&request.recipient_id!==account.id)notFound();
 if(!incoming&&request.recipient_id===account.id)redirect('/account/opportunities/'+id);
 const actor=request.buyer_id===account.id?'buyer':'recipient',events=await contactEvents(id,account.id),d=request.details;
 return <section className="account-page"><Link href={actor==='buyer'?'/account/contacts':'/account/opportunities'} className="text-sm text-[#365DC4]">← {actor==='buyer'?'Mis contactos':'Oportunidades'}</Link><header className="my-8"><div className="flex flex-wrap items-center justify-between gap-4"><h1 className="break-words text-4xl font-semibold tracking-tight">{request.project_name}</h1><RefreshContacts/></div><p className="mt-4 inline-block rounded-full bg-white px-4 py-2 text-sm">{contactStatuses[request.status]}</p><p className="mt-4 text-sm text-stone-500">{actor==='buyer'?'Solicitud entregada en la bandeja de la cuenta propietaria del proyecto.':'Solicitud enviada expresamente por el comprador.'} Solo ustedes pueden consultar este seguimiento.</p></header>
 <div className="grid items-start gap-12 xl:grid-cols-[minmax(0,1fr)_320px]"><div className="min-w-0"><h2 className="text-xl font-medium">Contexto compartido</h2><dl className="mt-6 grid gap-6 border-y border-stone-200 py-6 text-sm sm:grid-cols-2">{[['Nombre',d.name],['Correo de la cuenta',request.buyer_email],['Empresa',d.company],['Tamaño',d.size],['Plazo',d.timeline],['Presupuesto',d.budget||'No especificado'],['Necesidad',d.need]].map(([label,value])=><div key={label} className={label==='Necesidad'?'sm:col-span-2':''}><dt className="text-xs text-stone-500">{label}</dt><dd className="mt-2 whitespace-pre-wrap break-words">{value}</dd></div>)}</dl><p className="mt-4 text-xs leading-relaxed text-stone-400">Datos declarados por el comprador. El correo de la cuenta aún no tiene verificación de propiedad. Guardados, listas y notas privadas no se comparten.</p>
 <section className="mt-10"><h2 className="text-xl font-medium">Seguimiento</h2><ol className="mt-5 divide-y divide-stone-200">{events.map(event=><li key={event.id} className="py-5"><div className="flex flex-wrap items-center gap-3 text-xs text-stone-500"><span>{event.actor_id===request.buyer_id?'Comprador':'Proyecto'} · {contactStatuses[event.status]}</span><time dateTime={new Date(event.created_at).toISOString()}>{new Date(event.created_at).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Mexico_City'})} (CDMX)</time></div><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-relaxed">{event.message}</p></li>)}</ol></section></div>
 <section className="min-w-0 border-t border-stone-200 pt-6 xl:border-t-0 xl:pt-0"><h2 className="mb-5 text-xl font-medium">{actor==='buyer'?'Tu solicitud':'Responder al comprador'}</h2><ContactActions key={request.version} id={request.id} version={request.version} status={request.status} actor={actor}/></section></div>
 </section>;
}
