"use client";
import { useRef,useState } from 'react';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import { Camera } from 'lucide-react';
import { actionButtonStyle } from '@/lib/brand-colors';
export function AvatarForm({initial,name}:{initial:string|null;name:string}) {
 const [avatar,setAvatar]=useState(initial);const [pending,setPending]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const picker=useRef<HTMLInputElement>(null);const busy=useRef(false);const router=useRouter();
 async function save(file?:File){if(busy.current)return;setError('');setMessage('');if(file&&(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>2*1024*1024)){setError('Elige una foto JPG, PNG o WebP de hasta 2 MB.');return;}busy.current=true;setPending(true);try{const response=await fetch('/api/account/avatar',{method:file?'PUT':'DELETE',...(file?{headers:{'Content-Type':file.type},body:file}:{}),signal:AbortSignal.timeout(20000)});const data=await response.json();if(!response.ok)throw new Error(data.error);setAvatar(data.avatar??null);setMessage(file?'Tu foto está actualizada.':'Foto eliminada.');router.refresh();}catch{setError('No pudimos actualizar tu foto. Revisa el archivo e inténtalo de nuevo.');}finally{busy.current=false;setPending(false);}}
 return <div className="mb-8 border-b border-stone-200 pb-8"><div className="flex flex-wrap items-center gap-5"><div className="flex size-20 shrink-0 items-center justify-center overflow-hidden rounded-full text-2xl font-medium" style={actionButtonStyle}>{avatar?<Image src={avatar} width={80} height={80} unoptimized alt="Tu foto de perfil" className="size-20 object-cover"/>:name.slice(0,1).toUpperCase()}</div><div><div className="flex flex-wrap items-center gap-3"><input ref={picker} type="file" accept="image/jpeg,image/png,image/webp" aria-label="Seleccionar foto de perfil" className="sr-only" disabled={pending} onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(file)void save(file);}}/><button type="button" disabled={pending} onClick={()=>picker.current?.click()} style={actionButtonStyle} className="action-button inline-flex items-center gap-2 rounded-full px-4 py-2.5 text-sm disabled:opacity-50"><Camera className="size-4" aria-hidden="true"/>{pending?'Guardando…':'Cambiar foto'}</button>{avatar&&<button type="button" disabled={pending} onClick={()=>void save()} className="rounded-full px-3 py-2.5 text-sm text-stone-500 hover:text-stone-900">Quitar foto</button>}</div><p className="mt-3 text-xs text-stone-500">JPG, PNG o WebP · Hasta 2 MB</p></div></div>{error&&<p role="alert" className="mt-4 text-sm text-[#A94E35]">{error}</p>}{message&&<p role="status" className="mt-4 text-sm text-stone-600">{message}</p>}</div>;
}
